# 1. Создание и изменение массивов
## Описание задания:
- Создайте массив NumPy размером 3×3, содержащий числа от 1 до 9. 
- Умножьте все элементы массива на 2, а затем замените все элементы больше 10 на 0.
- Выведите итоговый массив.


In [10]:
import numpy as np

arr = np.arange(1,10).reshape(3,3)

arr = arr * 2

arr[arr > 10] = 0

print (arr)

[[ 2  4  6]
 [ 8 10  0]
 [ 0  0  0]]


# 2.Работа с булевыми масками
## Описание задания:
- Создайте массив NumPy из 20 случайных целых чисел от 1 до 100.
- Найдите и выведите все элементы, которые делятся на 5 без остатка. 
- Затем замените их на -1 и выведите обновленный массив.

In [11]:
import numpy as np

random_array = np.random.randint(1, 101, 20)
print("Исходный массив:", random_array)

divisible_by_5 = random_array[random_array % 5 == 0]
print("Элементы, делящиеся на 5:", divisible_by_5)

random_array[random_array % 5 == 0] = -1
print("Обновленный массив:", random_array)

Исходный массив: [80 50 62 58 24 61 18  2 61  3 14 87  3 26 70 27 22 70 30 67]
Элементы, делящиеся на 5: [80 50 70 70 30]
Обновленный массив: [-1 -1 62 58 24 61 18  2 61  3 14 87  3 26 -1 27 22 -1 -1 67]


# 3. Объединение и разбиение массивов

## Описание задания  
Создайте два массива NumPy размером 1×5, заполненные случайными числами от 0 до 50.

### Элементы задания:
- **Объедините** эти массивы в один двумерный массив (по строкам).
- **Разделите** полученный массив на два массива, каждый из которых содержит 5 элементов.
- **Выведите** все промежуточные и итоговые результаты.

Выведите все промежуточные и итоговые результаты.


In [12]:
import numpy as np

array1 = np.random.randint(0, 51, size=(1, 5))
array2 = np.random.randint(0, 51, size=(1, 5))

print("Первый массив:", array1)
print("Второй массив:", array2)

combined_array = np.concatenate((array1, array2), axis=0)

print("Объединенный массив:", combined_array)

array3 = combined_array[0, :]
array4 = combined_array[1, :]

print("Первый разделенный массив:", array3)
print("Второй разделенный массив:", array4)

Первый массив: [[ 6  7 35 45 26]]
Второй массив: [[ 2  9 37 41  2]]
Объединенный массив: [[ 6  7 35 45 26]
 [ 2  9 37 41  2]]
Первый разделенный массив: [ 6  7 35 45 26]
Второй разделенный массив: [ 2  9 37 41  2]


# 4.Генерация и работа с линейными последовательностями
## Описание задания:
- Создайте массив из 50 чисел, равномерно распределенных от -10 до 10.
- Вычислите сумму всех элементов, сумму положительных элементов и сумму отрицательных элементов.
- Выведите результаты.



In [13]:
import numpy as np

array = np.linspace(-10, 10, 50)

print("Массив:", array)

total_sum = np.sum(array)
print("Сумма всех элементов:", total_sum)

positive_elements = array[array > 0]
positive_sum = np.sum(positive_elements)
print("Сумма положительных элементов:", positive_sum)

negative_elements = array[array < 0]
negative_sum = np.sum(negative_elements)
print("Сумма отрицательных элементов:", negative_sum)

Массив: [-10.          -9.59183673  -9.18367347  -8.7755102   -8.36734694
  -7.95918367  -7.55102041  -7.14285714  -6.73469388  -6.32653061
  -5.91836735  -5.51020408  -5.10204082  -4.69387755  -4.28571429
  -3.87755102  -3.46938776  -3.06122449  -2.65306122  -2.24489796
  -1.83673469  -1.42857143  -1.02040816  -0.6122449   -0.20408163
   0.20408163   0.6122449    1.02040816   1.42857143   1.83673469
   2.24489796   2.65306122   3.06122449   3.46938776   3.87755102
   4.28571429   4.69387755   5.10204082   5.51020408   5.91836735
   6.32653061   6.73469388   7.14285714   7.55102041   7.95918367
   8.36734694   8.7755102    9.18367347   9.59183673  10.        ]
Сумма всех элементов: 7.105427357601002e-15
Сумма положительных элементов: 127.55102040816328
Сумма отрицательных элементов: -127.55102040816327


# 5.Работа с диагональными и единичными матрицами
## Описание задания:
Создайте: 
- Единичную матрицу размером 4×4.
- Диагональную матрицу размером 4×4 с диагональными элементами [5, 10, 15,20] (не использовать циклы).




In [14]:
import numpy as np

identity_matrix = np.eye(4)
print("Единичная матрица:\n", identity_matrix)

diagonal_matrix = np.diag([5, 10, 15, 20])
print("Диагональная матрица:\n", diagonal_matrix)

sum_identity = np.sum(identity_matrix)
sum_diagonal = np.sum(diagonal_matrix)

print("Сумма элементов единичной матрицы:", sum_identity)
print("Сумма элементов диагональной матрицы:", sum_diagonal)

if sum_identity > sum_diagonal:
    print("Сумма элементов единичной матрицы больше.")
elif sum_identity < sum_diagonal:
    print("Сумма элементов диагональной матрицы больше.")
else:
    print("Суммы элементов матриц равны.")

Единичная матрица:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Диагональная матрица:
 [[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]]
Сумма элементов единичной матрицы: 4.0
Сумма элементов диагональной матрицы: 50
Сумма элементов диагональной матрицы больше.


# 6.Создание и базовые операции с матрицами
## Описание задания:
Создайте две квадратные матрицы NumPy размером 3×3, заполненные
случайными целыми числами от 1 до 20. Вычислите и выведите:
- Их сумму
- Их разность
- Их поэлементное произведение



In [15]:
import numpy as np

matrix1 = np.random.randint(1, 21, size=(3, 3))
matrix2 = np.random.randint(1, 21, size=(3, 3))

print("Первая матрица:\n", matrix1)
print("Вторая матрица:\n", matrix2)

sum_matrix = matrix1 + matrix2
print("Сумма матриц:\n", sum_matrix)

difference_matrix = matrix1 - matrix2
print("Разность матриц:\n", difference_matrix)

elementwise_product = matrix1 * matrix2
print("Поэлементное произведение:\n", elementwise_product)

Первая матрица:
 [[12  2  8]
 [19  3  2]
 [ 4 20 13]]
Вторая матрица:
 [[13 20 12]
 [19 18 11]
 [ 4 13 16]]
Сумма матриц:
 [[25 22 20]
 [38 21 13]
 [ 8 33 29]]
Разность матриц:
 [[ -1 -18  -4]
 [  0 -15  -9]
 [  0   7  -3]]
Поэлементное произведение:
 [[156  40  96]
 [361  54  22]
 [ 16 260 208]]


# 7.Умножение матриц
## Описание задания:
Создайте две матрицы NumPy:
- Первую размером 2×3, заполненную случайными числами от 1 до 10.
- Вторую размером 3×2, заполненную случайными числами от 1 до 10.
  
Выполните матричное умножение ( @ или np.dot ) и выведите результат.


In [16]:
import numpy as np

matrix1 = np.random.randint(1, 11, size=(2, 3))

matrix2 = np.random.randint(1, 11, size=(3, 2))

print("Первая матрица:\n", matrix1)
print("Вторая матрица:\n", matrix2)

result_matrix = matrix1 @ matrix2

print("Результат матричного умножения:\n", result_matrix)

Первая матрица:
 [[8 9 9]
 [8 9 8]]
Вторая матрица:
 [[9 4]
 [2 9]
 [6 7]]
Результат матричного умножения:
 [[144 176]
 [138 169]]


# 8.Опеределитель и обратная матрица
## Описание задания:
Создайте случайную квадратную матрицу 3×3. Найдите и выведите:
- Определитель этой матрицы
- Обратную матрицу (если существует, иначе выведите сообщение, что матрица
вырождена)
  


In [17]:
import numpy as np

matrix = np.random.rand(3, 3)
print("Матрица:\n", matrix)

determinant = np.linalg.det(matrix)
print("Определитель матрицы:", determinant)

if np.abs(determinant) > 1e-8:
    try:
        inverse_matrix = np.linalg.inv(matrix)
        print("Обратная матрица:\n", inverse_matrix)
    except np.linalg.LinAlgError:
        print("Матрица вырождена и не имеет обратной матрицы.")
else:
    print("Матрица вырождена и не имеет обратной матрицы.")

Матрица:
 [[0.45258824 0.7172766  0.99107246]
 [0.0268598  0.53104092 0.76429545]
 [0.06923236 0.18400502 0.14661309]]
Определитель матрицы: -0.02482142600139072
Обратная матрица:
 [[ 2.52913137 -3.11022277 -0.8827542 ]
 [-1.97313332  0.09100716 12.86352878]
 [ 1.282073    1.35446499 -8.90669896]]


# 9.Транспанирование и след матрицы
## Описание задания:
Создайте матрицу NumPy размером 4×4, содержащую случайные целые числа от1 до 50. 

Выведите:
- Исходную матрицу
- Транспонированную матрицу
- След матрицы (сумму элементов на главной диагонали)



In [18]:
import numpy as np

matrix = np.random.randint(1, 51, size=(4, 4))

print("Исходная матрица:\n", matrix)

transposed_matrix = matrix.T
print("Транспонированная матрица:\n", transposed_matrix)

trace = np.trace(matrix)
print("След матрицы:", trace)

Исходная матрица:
 [[10 29 28 14]
 [28 18 17 19]
 [18  3 14 48]
 [48 16 48 10]]
Транспонированная матрица:
 [[10 28 18 48]
 [29 18  3 16]
 [28 17 14 48]
 [14 19 48 10]]
След матрицы: 52


# 10.Системы линейных уравнений
## Описание задания:
Решите систему линейных уравнений вида:


\begin{aligned}
2x + 3y - z &= 5 \\
4x - y + 2z &= 6 \\
-3x + 5y + 4z &= -2
\end{aligned}



In [19]:
import numpy as np

A = np.array([[2, 3, -1],
              [4, -1, 2],
              [-3, 5, 4]])

B = np.array([5, 6, -2])

X = np.linalg.solve(A, B)

print("Решение системы уравнений:")
print("x =", X[0])
print("y =", X[1])
print("z =", X[2])

Решение системы уравнений:
x = 1.6396396396396398
y = 0.5765765765765767
z = 0.009009009009008978


# 11.Индивидуальное задание (Вариант 7)
## Описание задания:
Решите индивидуальное задание согласно варианта. Каждое задание
предусматривает построение системы линейных уравнений. Решите полученную
систему уравнений с использованием библиотеки NumPy. Для решения системы
используйте метод Крамера и матричный метод. Сравните полученные
результаты, с результатами, полученными с помощью np.linalg.solve .
## 7 задание:

\begin{cases}
x = \frac{2}{3}y \\
z = x + y + 100 \\
x + y + z = 1000
\end{cases}



In [20]:
import numpy as np
import numpy.linalg

A = np.array([[3, -2, 0],
              [1, 1, -1],
              [1, 1, 1]])

B = np.array([0, -100, 1000])

def kramer(A, B):
    det_A = np.linalg.det(A)
    if np.isclose(det_A, 0):
        return None
    n = A.shape[0]
    X = np.array([np.linalg.det(np.concatenate((A[:,:i], B[:,None], A[:,i+1:]), axis=1)) / det_A for i in range(n)])
    return X

def inverse_matrix_method(A, B):
  try:
    A_inv = np.linalg.inv(A)
  except np.linalg.LinAlgError:
    return None
  X = np.dot(A_inv, B)
  return X

def numpy_solve(A, B):
  try:
    X = np.linalg.solve(A, B)
    return X
  except np.linalg.LinAlgError:
    return None

X_kramer = kramer(A, B)
X_inverse = inverse_matrix_method(A, B)
X_solve = numpy_solve(A, B)

print("Результаты решения системы уравнений:")

if X_kramer is not None:
  print("\nМетод Крамера:")
  print("Цена первого товара =", X_kramer[0])
  print("Цена второго товара =", X_kramer[1])
  print("Цена третьего товара =", X_kramer[2])
else:
  print("\nМетод Крамера: Решение не существует (определитель равен 0).")

if X_inverse is not None:
  print("\nМатричный метод (через обратную матрицу):")
  print("Цена первого товара =", X_inverse[0])
  print("Цена второго товара =", X_inverse[1])
  print("Цена третьего товара =", X_inverse[2])
else:
  print("\nМатричный метод (через обратную матрицу): Решение не существует (матрица вырождена).")

if X_solve is not None:
  print("\nnp.linalg.solve:")
  print("Цена первого товара =", X_solve[0])
  print("Цена второго товара =", X_solve[1])
  print("Цена третьего товара =", X_solve[2])
else:
    print("\nnp.linalg.solve: Решение не существует (матрица вырождена).")

if X_kramer is not None and X_inverse is not None and X_solve is not None:
    results = [X_kramer, X_inverse, X_solve]
    if all(np.allclose(results[0], x) for x in results[1:]):
        print("\nВсе методы дали одинаковые результаты.")
    else:
        print("\nВнимание! Методы дали разные результаты.")

Результаты решения системы уравнений:

Метод Крамера:
x (Первый резервуар) = 225.00000000000003
y (Второй резервуар) = 112.50000000000001
z (Третий резервуар) = 162.49999999999997

Матричный метод (через обратную матрицу):
x (Первый резервуар) = 225.0
y (Второй резервуар) = 112.5
z (Третий резервуар) = 162.5

np.linalg.solve:
x (Первый резервуар) = 225.0
y (Второй резервуар) = 112.5
z (Третий резервуар) = 162.5

Все методы дали одинаковые результаты.
